lastfm:
  applicationName: "lastfm-scrobbler"
  apiKey: ""
  sharedSecret: ""
  registeredTo: ""
  userLoginToken: ""
  userUsername: ""
  userPassword: ""

musixmatch:
  apiKey: ""

log:
  path: "logs/go_lastfm-scrobbler.log"
  level: "info"

database:
  path: "storage/tracks.db"

http:
  port: "8080"

telemetry:
  name: "lastfm-scrobbler"
